### ISSUE TITLE
Heroku post-deploy hook interferes with scalingo auto-deploy.

### ISSUE THREAD

**Issue by webplate** [covoiturage-libre/covoiturage-libre#199]
### Current Behavior 
The cloud service we are using (scalingo) misses auto deployment functionality. It reads from `app.json` and executes its postdeploy hook which crashes the deployment.

```
rake aborted!
 [postdeploy-3339] [stderr] ActiveRecord::StatementInvalid: PG::DuplicateObject: ERROR:  extension "postgis" already exists
```

### Expected Behaviour 
We should be able to deploy to  scalingo with all the functionalities.

### Steps to Reproduce the Problem  
Set scalingo to deploy from github directly.

[x] Development
[] Production

### Ideas for solving the problem / Implementing the new functionality  
Modify `lib/tasks/db.rake` to check for an already enabled post-gis extension.
Rake should not try to create the extension if it is already enabled as this crashes the deployment.

@nicolasleger I need your help with this issue as you are the one using heroku.

**Comment by webplate** [comment]
@nicolasleger this problem follows your commit https://github.com/covoiturage-libre/covoiturage-libre/commit/0c7381d833f3fe46c7c2a06c48a75e9308c9056e
I want to keep heroku deployment. Does it need app.json ?

**Comment by nicolasleger** [comment]
Yes `app.json` references some plugins and install them.

We can guard the task to check if extension is not enable:
https://github.com/covoiturage-libre/covoiturage-libre/blob/master/lib/tasks/db.rake

**Comment by webplate** [comment]
Can you PR ? Would be wonderful !
I'll check on scalingo and merge :)

**Comment by nicolasleger** [comment]
done https://github.com/covoiturage-libre/covoiturage-libre/pull/200 but quite ugly
better to filter exception to only mute the one if already enable or find SQL query to check if enable before

**Comment by nicolasleger** [comment]
Updated via https://github.com/covoiturage-libre/covoiturage-libre/pull/201/

@webplate can you check it ?

**Comment by nicolasleger** [comment]
Maybe https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fcovoiturage-libre%2Fcovoiturage-libre%3Fbranch%3Dnicolasleger%3Apatch-1

**Comment by nicolasleger** [comment]
It fails on my side at another state.
Probably because `ELASTICSEARCH_URL` is not defined automatically from Searchbox free Heroku addon.

```
public.fr/particuliers/vosdroits/F31403)"], ["created_at", "2017-08-29 14:46:15.982969"], ["updated_at", "2017-08-29 14:46:15.982969"]]
  [1m[35m (1.8ms)[0m  [1m[35mCOMMIT[0m
rake aborted!
Faraday::ConnectionFailed: Couldn't connect to server
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:106:in `block in request'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:127:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/operations.rb:35:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.10.1/lib/ethon/easy/response_callbacks.rb:68:in `complete'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.10.1/lib/ethon/easy/operations.rb:33:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/operations.rb:16:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/cacheable.rb:18:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/block_connection.rb:31:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/stubbable.rb:25:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/request/before.rb:26:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-1.1.2/lib/typhoeus/adapters/faraday.rb:72:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/middleware.rb:9:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/base.rb:258:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-2.0.2/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-api-2.0.2/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/elasticsearch-api-2.0.2/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/index.rb:158:in `all_indices'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/index.rb:168:in `clean_indices'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/index.rb:199:in `reindex_scope'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/model.rb:53:in `searchkick_reindex'
/app/vendor/bundle/ruby/2.4.0/gems/searchkick-1.4.2/lib/searchkick/tasks.rb:9:in `block (2 levels) in <top (required)>'
Tasks: TOP => searchkick:reindex
(See full trace by running task with --trace)
```

**Comment by webplate** [comment]
I cannot test heroku but your PR fixes the scalingo problem !
I will merge this except if you want to investigate more about elastic search on free heroku plan.

**Comment by webplate** [comment]
Fixed !
